name: Docker image build and push
on: [push]
jobs:
  Docker-Build-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: dockerhub login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
#      - name: buildx image
#        run: |
#          docker buildx create --name mybuilder --use
#          docker buildx ls
#          docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 -t yokoshin12/flask-redis:latest .
#          docker build -t yokoshin12/flask-redis:latest .
#      - name: list docker image
#        run: docker image ls
#      - name: push to dockerhub
#        run: docker image push yokoshin12/flask-redis:latest
